'use client'

import { useMemo, useState } from 'react'
import { Bell, Bookmark, BriefcaseBusiness, ChevronDown, ChevronLeft, Hash, Home, LockKeyhole, Menu, MessageCircle, MoreHorizontal, Plus, Search, Send, Share2, TrendingUp, Users, X, ArrowBigUp, CircleHelp } from 'lucide-react'

const posts = [
  { id: 1, type: 'editorial', author: 'DevNodo', initials: 'DN', badge: 'Staff DevNodo', time: 'hace 2h', tag: 'nextjs', title: 'Next.js 16: lo que realmente cambia para tu próximo proyecto', excerpt: 'Un recorrido práctico por Cache Components, React Compiler y las nuevas APIs que ya puedes usar.', stack: ['Next.js', 'React', 'Rendimiento'], votes: 248, comments: 38 },
  { id: 2, type: 'job', author: 'Bot Vacantes', initials: 'BV', badge: 'Bot Vacantes', time: 'hace 3h', tag: 'empleos', title: 'Buscamos Senior React + Node.js para producto fintech', excerpt: 'Equipo remoto en Latam. Necesitamos a alguien que disfrute construyendo productos con impacto real.', stack: ['React', 'Node.js', 'Remote'], votes: 96, comments: 14 },
  { id: 3, type: 'discussion', author: 'Sofía Herrera', initials: 'SH', badge: 'Dev', time: 'hace 4h', tag: 'debate', title: '¿Seguimos necesitando una capa de estado global en 2026?', excerpt: 'Entre Server Components, URL state y signals, mi store cada vez tiene menos responsabilidades.', stack: ['React', 'Arquitectura'], votes: 184, comments: 62 },
  { id: 4, type: 'showcase', author: 'Mateo Lima', initials: 'ML', badge: 'Dev', time: 'ayer', tag: 'showcase', title: 'Lancé una herramienta para visualizar tus queries de PostgreSQL', excerpt: 'Una pequeña utilidad open source para entender planes de ejecución sin salir del editor.', stack: ['PostgreSQL', 'TypeScript', 'Open Source'], votes: 132, comments: 21 },
]
const topics = ['nextjs', 'react', 'typescript', 'empleos', 'postgresql', 'ia', 'remoto']
const navItems = [['Inicio', Home], ['Explorar', TrendingUp], ['Empleos', BriefcaseBusiness], ['Tags', Hash], ['Guardados', Bookmark]] as const

function Avatar({ initials }: { initials: string }) { return <div className="avocado-avatar">{initials}</div> }
function Sidebar({ active, setActive, onPublish }: { active: string; setActive: (v: string) => void; onPublish: () => void }) { return <aside className="avocado-sidebar"><div className="avocado-brand"><div className="brand-fruit">D</div><div><strong>DevNodo</strong><span>COMUNIDAD TECH</span></div><button className="collapse"><ChevronLeft /></button></div><div className="side-body"><p className="side-label">NAVEGACIÓN</p>{navItems.map(([label, Icon]) => <button key={label} onClick={() => setActive(label)} className={`avocado-nav ${active === label ? 'active' : ''}`}><Icon />{label}</button>)}<button className="side-new" onClick={onPublish}><Plus /> Crear publicación</button></div><div className="side-profile"><Avatar initials="KG" /><div><strong>Kevin Garza</strong><span>Pro</span></div><ChevronDown /></div></aside> }
function Topbar({ onPublish, search, setSearch, onMenu }: { onPublish: () => void; search: string; setSearch: (v: string) => void; onMenu: () => void }) { return <header className="avocado-topbar"><button className="mobile-menu" onClick={onMenu}><Menu /></button><div className="crumbs"><strong>DevNodo</strong><span>Inicio</span></div><div className="avocado-search"><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar en DevNodo..." /></div><button className="new-article" onClick={onPublish}><Plus /> Crear publicación</button><button className="bell"><Bell /></button></header> }
function PostCard({ post, onUnlock, voted, setVoted }: { post: typeof posts[number]; onUnlock: () => void; voted: number[]; setVoted: (v: number[]) => void }) { const isVoted = voted.includes(post.id); return <article className="feed-card"><div className="feed-author"><Avatar initials={post.initials} /><div><strong>{post.author}</strong><span>{post.badge} · {post.time} · #{post.tag}</span></div><MoreHorizontal /></div><h3>{post.title}</h3><p>{post.excerpt}</p><div className="chips">{post.stack.map(s => <span key={s}>{s}</span>)}</div>{post.type === 'job' && <button className="contact-link" onClick={onUnlock}><LockKeyhole /> Ver contacto directo</button>}<div className="feed-actions"><button onClick={() => setVoted(isVoted ? voted.filter(i => i !== post.id) : [...voted, post.id])} className={isVoted ? 'is-voted' : ''}><ArrowBigUp /> {post.votes + (isVoted ? 1 : 0)}</button><span><MessageCircle /> {post.comments}</span><span className="grow" /><button aria-label="Guardar publicación"><Bookmark /></button><button aria-label="Compartir publicación"><Share2 /></button></div></article> }
function Feed({ search, onUnlock }: { search: string; onUnlock: () => void }) { const [tab, setTab] = useState('Tendencias'); const [voted, setVoted] = useState<number[]>([]); const filtered = useMemo(() => posts.filter(p => `${p.title} ${p.excerpt} ${p.stack.join(' ')} ${p.tag}`.toLowerCase().includes(search.toLowerCase()) && (tab !== 'Vacantes & Freelance' || p.type === 'job')), [search, tab]); return <section className="feed-section"><div className="section-title"><div><p className="soft-kicker">FEED DE LA COMUNIDAD</p><h2>Lo que está pasando en DevNodo</h2><p className="section-subtitle">Conversaciones reales, proyectos en marcha y oportunidades compartidas por la comunidad.</p></div><div className="feed-tabs">{['Tendencias', 'Últimos Envíos', 'Vacantes & Freelance'].map(item => <button className={tab === item ? 'selected' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div></div><div className="feed-grid">{filtered.map(post => <PostCard key={post.id} post={post} onUnlock={onUnlock} voted={voted} setVoted={setVoted} />)}</div>{filtered.length === 0 && <div className="empty-state"><Search /><h3>No encontramos publicaciones</h3><p>Prueba con otra búsqueda o explora todos los envíos.</p></div>}</section> }
function PublishModal({ close }: { close: () => void }) { const [preview, setPreview] = useState(false); return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><section className="avocado-modal" role="dialog" aria-modal="true"><button className="modal-x" onClick={close}><X /></button><p className="soft-kicker">NUEVA PUBLICACIÓN</p><h2>Comparte algo con la comunidad</h2><div className="modal-tabs"><button className="selected">Discusión</button><button>Artículo</button><button>Oportunidad</button></div><div className="editor-tools"><span>MARKDOWN</span><button onClick={() => setPreview(!preview)}>{preview ? 'Editar' : 'Vista previa'}</button></div>{preview ? <div className="preview-copy"><p className="soft-kicker">VISTA PREVIA</p><h3>Tu publicación aparecerá aquí</h3><p>Revisa cómo se verá antes de compartirla.</p></div> : <textarea aria-label="Contenido de la publicación" placeholder="¿Qué estás construyendo, aprendiendo o pensando?" />}<div className="modal-footer"><span><Hash /> Añadir tags</span><button className="new-article" onClick={close}>Publicar <Send /></button></div></section></div> }
function AuthModal({ close }: { close: () => void }) { return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><section className="auth-box" role="dialog" aria-modal="true"><button className="modal-x" onClick={close}><X /></button><LockKeyhole /><p className="soft-kicker">CONTACTO DIRECTO</p><h2>Desbloquea esta oportunidad</h2><p>Regístrate para acceder a los datos de contacto y unirte a la conversación.</p><button className="auth-action" onClick={close}>Continuar con GitHub</button><button className="auth-action secondary" onClick={close}>Continuar con Google</button></section></div> }
export function CommunityHub() { const [active, setActive] = useState('Inicio'); const [search, setSearch] = useState(''); const [publish, setPublish] = useState(false); const [auth, setAuth] = useState(false); const [menu, setMenu] = useState(false); return <div className="avocado-app"><Sidebar active={active} setActive={setActive} onPublish={() => setPublish(true)} /><div className="avocado-main"><Topbar onPublish={() => setPublish(true)} search={search} setSearch={setSearch} onMenu={() => setMenu(!menu)} /><main className="forum-content"><div className="forum-heading"><div><div className="dashboard-icon forum-mark"><Hash /></div><div><h1>La comunidad de developers</h1><p>Comparte lo que sabes, pregunta sin miedo y encuentra tu próximo proyecto.</p></div></div><button className="help-button"><CircleHelp /> Normas de la comunidad</button></div><div className="forum-layout"><div className="forum-main"><div className="topic-strip"><strong>Explora temas</strong>{topics.map(topic => <button key={topic} onClick={() => setSearch(topic)}>#{topic}</button>)}</div><Feed search={search} onUnlock={() => setAuth(true)} /></div><aside className="forum-rail"><section className="rail-card"><div className="rail-heading"><h3>Trending ahora</h3><TrendingUp /></div>{topics.slice(0, 5).map((topic, i) => <button className="trend-row" key={topic} onClick={() => setSearch(topic)}><span>#{topic}</span><small>{[248, 186, 142, 96, 74][i]} publicaciones</small></button>)}</section><section className="rail-card join-card"><div className="join-icon"><Users /></div><h3>Haz crecer la comunidad</h3><p>Comparte tu experiencia y encuentra nuevas oportunidades.</p><button className="side-new" onClick={() => setPublish(true)}><Plus /> Crear publicación</button></section></aside></div></main></div>{menu && <div className="mobile-nav">{navItems.slice(0, 5).map(([label, Icon]) => <button key={label} onClick={() => { setActive(label); setMenu(false) }} className={active === label ? 'active' : ''}><Icon /><span>{label}</span></button>)}</div>}{publish && <PublishModal close={() => setPublish(false)} />}{auth && <AuthModal close={() => setAuth(false)} />}</div> }
