'use client'

import { useMemo, useState } from 'react'
import { Bell, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Eye, FileText, Hash, Home, LayoutGrid, Menu, MoreHorizontal, PenLine, Plus, Search, Send, Settings, Share2, Sparkles, TrendingDown, Users, X, ArrowUpRight, LockKeyhole, Bookmark, ArrowBigUp, MessageCircle } from 'lucide-react'

const posts = [
  { id: 1, type: 'editorial', author: 'Avocado Studio', initials: 'AS', badge: 'Staff Avocado', time: 'hace 2h', tag: 'nextjs', title: 'Next.js 16: lo que realmente cambia para tu próximo proyecto', excerpt: 'Un recorrido práctico por Cache Components, React Compiler y las nuevas APIs que ya puedes usar.', stack: ['Next.js', 'React', 'Rendimiento'], votes: 248, comments: 38 },
  { id: 2, type: 'job', author: 'Bot Vacantes', initials: 'BV', badge: 'Bot Vacantes', time: 'hace 3h', tag: 'empleos', title: 'Buscamos Senior React + Node.js para producto fintech', excerpt: 'Equipo remoto en Latam. Necesitamos a alguien que disfrute construyendo productos con impacto real.', stack: ['React', 'Node.js', 'Remote'], votes: 96, comments: 14 },
  { id: 3, type: 'discussion', author: 'Sofía Herrera', initials: 'SH', badge: 'Dev', time: 'hace 4h', tag: 'debate', title: '¿Seguimos necesitando una capa de estado global en 2026?', excerpt: 'Entre Server Components, URL state y signals, mi store cada vez tiene menos responsabilidades.', stack: ['React', 'Arquitectura'], votes: 184, comments: 62 },
  { id: 4, type: 'showcase', author: 'Mateo Lima', initials: 'ML', badge: 'Dev', time: 'ayer', tag: 'showcase', title: 'Lancé una herramienta para visualizar tus queries de PostgreSQL', excerpt: 'Una pequeña utilidad open source para entender planes de ejecución sin salir del editor.', stack: ['PostgreSQL', 'TypeScript', 'Open Source'], votes: 132, comments: 21 },
]
const channels = [{ name: 'Blog', color: 'purple', value: '19', stats: ['34', '34', '0'], labels: ['visitas', 'visitantes', 'likes'] }, { name: 'Substack', color: 'red', value: '10', stats: ['688', '10', '45%'], labels: ['visitas', 'posts', 'apertura'] }, { name: 'LinkedIn', color: 'blue', value: '4', stats: ['0', '0', '0'], labels: ['visitas', 'visitantes', 'likes'] }]

function Avatar({ initials }: { initials: string }) { return <div className="avocado-avatar">{initials}</div> }
function Sidebar({ active, setActive, onPublish }: { active: string; setActive: (v: string) => void; onPublish: () => void }) {
  const items = [['Calendario Editorial', CalendarDays], ['Banco de Temas', Sparkles], ['Redactor IA', PenLine], ['LinkedIn', Users], ['Substack', FileText], ['Web', LayoutGrid]] as const
  return <aside className="avocado-sidebar"><div className="avocado-brand"><div className="brand-fruit">●</div><div><strong>Avocado</strong><span>ESTUDIO</span></div><button className="collapse"><ChevronLeft /></button></div><div className="side-body"><p className="side-label">PRINCIPAL</p>{items.map(([label, Icon]) => <button key={label} onClick={() => setActive(label)} className={`avocado-nav ${active === label ? 'active' : ''}`}><Icon />{label}</button>)}<button className="side-new" onClick={onPublish}><Plus /> Nuevo contenido</button></div><div className="side-profile"><Avatar initials="KG" /><div><strong>Kevin Garza</strong><span>Pro</span></div><ChevronDown /></div></aside>
}
function Topbar({ onPublish, search, setSearch, onMenu }: { onPublish: () => void; search: string; setSearch: (v: string) => void; onMenu: () => void }) { return <header className="avocado-topbar"><button className="mobile-menu" onClick={onMenu}><Menu /></button><div className="crumbs"><span>Inicio</span><b>/</b><strong>Resumen General</strong></div><div className="avocado-search"><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar contenido, canales, tendencias..." /></div><button className="new-article" onClick={onPublish}><Plus /> Nuevo artículo</button><button className="bell"><Bell /></button></header> }
function Metric({ icon: Icon, label, value, tone }: { icon: typeof Eye; label: string; value: string; tone: string }) { return <div className={`metric ${tone}`}><div className="metric-head"><span>{label}</span><Icon /></div><strong>{value}</strong></div> }
function CommunityFeed({ search, onUnlock }: { search: string; onUnlock: () => void }) { const [tab, setTab] = useState('Tendencias'); const [voted, setVoted] = useState<number[]>([]); const filtered = useMemo(() => posts.filter(p => `${p.title} ${p.excerpt} ${p.stack.join(' ')}`.toLowerCase().includes(search.toLowerCase()) && (tab === 'Tendencias' || tab === 'Últimos Envíos' || tab === 'Vacantes & Freelance' && p.type === 'job')), [search, tab]); return <section className="feed-section"><div className="section-title"><div><p className="soft-kicker">COMUNIDAD DEVNODO</p><h2>Conversaciones y oportunidades</h2></div><div className="feed-tabs">{['Tendencias', 'Últimos Envíos', 'Vacantes & Freelance'].map(item => <button className={tab === item ? 'selected' : ''} key={item} onClick={() => setTab(item)}>{item}</button>)}</div></div><div className="feed-grid">{filtered.map(post => <article className="feed-card" key={post.id}><div className="feed-author"><Avatar initials={post.initials} /><div><strong>{post.author}</strong><span>{post.badge} · {post.time} · #{post.tag}</span></div><MoreHorizontal /></div><h3>{post.title}</h3><p>{post.excerpt}</p><div className="chips">{post.stack.map(s => <span key={s}>{s}</span>)}</div>{post.type === 'job' && <button className="contact-link" onClick={onUnlock}><LockKeyhole /> Ver contacto directo</button>}<div className="feed-actions"><button onClick={() => setVoted(v => v.includes(post.id) ? v.filter(i => i !== post.id) : [...v, post.id])} className={voted.includes(post.id) ? 'is-voted' : ''}><ArrowBigUp /> {post.votes + (voted.includes(post.id) ? 1 : 0)}</button><span><MessageCircle /> {post.comments}</span><span className="grow" /><button><Bookmark /></button><button><Share2 /></button></div></article>)}</div></section> }
function PublishModal({ close }: { close: () => void }) { const [preview, setPreview] = useState(false); return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><section className="avocado-modal" role="dialog" aria-modal="true"><button className="modal-x" onClick={close}><X /></button><p className="soft-kicker">NUEVO CONTENIDO</p><h2>¿Qué quieres publicar?</h2><div className="modal-tabs"><button className="selected">Artículo</button><button>Newsletter</button><button>Post social</button></div><div className="editor-tools"><span>MARKDOWN</span><button onClick={() => setPreview(!preview)}>{preview ? 'Editar' : 'Vista previa'}</button></div>{preview ? <div className="preview-copy"><p className="soft-kicker">VISTA PREVIA</p><h3>Tu contenido aparecerá aquí</h3><p>Revisa cómo se verá antes de publicarlo.</p></div> : <textarea aria-label="Contenido del artículo" placeholder="Escribe una idea, artículo o actualización..." />}<div className="modal-footer"><span><Hash /> Añadir tags</span><button className="new-article" onClick={close}>Publicar <Send /></button></div></section></div> }
function AuthModal({ close }: { close: () => void }) { return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && close()}><section className="auth-box" role="dialog" aria-modal="true"><button className="modal-x" onClick={close}><X /></button><LockKeyhole /><p className="soft-kicker">CONTACTO DIRECTO</p><h2>Desbloquea esta oportunidad</h2><p>Regístrate para acceder a los datos de contacto y unirte a la conversación.</p><button className="auth-action" onClick={close}>Continuar con GitHub</button><button className="auth-action secondary" onClick={close}>Continuar con Google</button></section></div> }
export function CommunityHub() { const [active, setActive] = useState('Resumen General'); const [search, setSearch] = useState(''); const [publish, setPublish] = useState(false); const [auth, setAuth] = useState(false); const [menu, setMenu] = useState(false); return <div className="avocado-app"><Sidebar active={active} setActive={setActive} onPublish={() => setPublish(true)} /><div className="avocado-main"><Topbar onPublish={() => setPublish(true)} search={search} setSearch={setSearch} onMenu={() => setMenu(!menu)} /><main className="dashboard-content"><div className="dashboard-heading"><div><div className="dashboard-icon"><Home /></div><div><h1>Dashboard</h1><p>Buen día, Kevin. Aquí está el resumen de tu estrategia de contenido.</p></div></div><button className="month-select"><CalendarDays /> Agosto 2026 <ChevronDown /></button></div><section className="analytics-panel"><h2>Analytics — Agosto 2026</h2><div className="metric-grid"><Metric icon={Eye} label="Visitas" value="722" tone="green" /><Metric icon={Users} label="Visitantes únicos" value="44" tone="violet" /><Metric icon={TrendingDown} label="Scroll promedio" value="65%" tone="orange" /><Metric icon={Share2} label="Shares" value="0" tone="blue" /></div><div className="channel-grid">{channels.map(channel => <div className="channel-card" key={channel.name}><div className="channel-head"><span><i className={channel.color} />{channel.name}</span><b>{channel.value}</b></div><div className="channel-stats">{channel.stats.map((stat, i) => <div key={stat + i}><strong>{stat}</strong><small>{channel.labels[i]}</small></div>)}</div></div>)}</div></section><div className="bottom-panels"><section className="content-month panel"><div className="panel-heading"><h2>Contenido del mes</h2><span>27 total</span></div>{[['Blog Posts', '19', 'purple'], ['Newsletters', '4', 'red'], ['LinkedIn Posts', '4', 'blue']].map(([name, number, color]) => <div className="content-row" key={name}><span><i className={color} />{name}</span><b className={color}>{number}</b></div>)}</section><section className="upcoming panel"><div className="panel-heading"><h2>Próximas publicaciones</h2><button>Ver calendario <ArrowUpRight /></button></div><div className="empty-schedule"><CalendarDays /><p>Sin publicaciones agendadas</p><button onClick={() => setPublish(true)}>Ir al calendario</button></div></section></div><CommunityFeed search={search} onUnlock={() => setAuth(true)} /></main></div>{(publish || auth) && (publish ? <PublishModal close={() => setPublish(false)} /> : <AuthModal close={() => setAuth(false)} />)}{menu && <button className="mobile-overlay" onClick={() => setMenu(false)} aria-label="Cerrar menú" />}</div> }
