'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import {
  Bell, Bookmark, BriefcaseBusiness, ChevronDown, Code2, Compass, Flame,
  Hash, Home, Menu, MessageCircle, MoreHorizontal, PenLine, Plus, Search,
  Send, Share2, ShieldCheck, Sparkles, Tag, TrendingUp, Trophy, Users, X,
  Zap, ArrowBigUp, LockKeyhole, CheckCircle2
} from 'lucide-react'

const posts = [
  { id: 1, type: 'editorial', author: 'Avocado Studio', initials: 'AS', badge: 'Staff Avocado', time: 'hace 2h', tag: 'nextjs', title: 'Next.js 16: lo que realmente cambia para tu próximo proyecto', excerpt: 'Un recorrido práctico por Cache Components, React Compiler y las nuevas APIs que ya puedes usar.', stack: ['Next.js', 'React', 'Rendimiento'], votes: 248, comments: 38, color: 'cyan' },
  { id: 2, type: 'job', author: 'Bot Vacantes', initials: 'BV', badge: 'Bot Vacantes', time: 'hace 3h', tag: 'empleos', title: 'Buscamos Senior React + Node.js para producto fintech', excerpt: 'Equipo remoto en Latam. Necesitamos a alguien que disfrute construyendo productos con impacto real.', stack: ['React', 'Node.js', 'Remote'], votes: 96, comments: 14, budget: '$35–50 / hr', color: 'emerald' },
  { id: 3, type: 'discussion', author: 'Sofía Herrera', initials: 'SH', badge: 'Dev', time: 'hace 4h', tag: 'debate', title: '¿Seguimos necesitando una capa de estado global en 2026?', excerpt: 'Entre Server Components, URL state y signals, mi store cada vez tiene menos responsabilidades. ¿Cómo lo están resolviendo?', stack: ['React', 'Arquitectura'], votes: 184, comments: 62, color: 'blue' },
  { id: 4, type: 'showcase', author: 'Mateo Lima', initials: 'ML', badge: 'Dev', time: 'ayer', tag: 'showcase', title: 'Lancé una herramienta para visualizar tus queries de PostgreSQL', excerpt: 'Una pequeña utilidad open source para entender planes de ejecución sin salir del editor.', stack: ['PostgreSQL', 'TypeScript', 'Open Source'], votes: 132, comments: 21, color: 'violet' },
]

const navItems = [
  { label: 'Inicio', icon: Home }, { label: 'Explorar', icon: Compass },
  { label: 'Empleos', icon: BriefcaseBusiness, count: '12' }, { label: 'Showcase', icon: Trophy },
]
const tags = ['javascript', 'react', 'nextjs', 'python', 'ia', 'empleos']
const tabs = [{ label: 'Tendencias', icon: Flame }, { label: 'Últimos Envíos', icon: Zap }, { label: 'Vacantes & Freelance', icon: BriefcaseBusiness }, { label: 'Showcase Projects', icon: Sparkles }]

function Avatar({ initials, tone = 'cyan' }: { initials: string; tone?: string }) {
  return <div className={`avatar avatar-${tone}`} aria-hidden="true">{initials}</div>
}

function LeftSidebar({ onPublish, activeTab, setActiveTab }: { onPublish: () => void; activeTab: string; setActiveTab: (v: string) => void }) {
  return <aside className="left-sidebar">
    <div className="sidebar-section">
      <p className="eyebrow">Comunidad</p>
      <nav className="nav-list" aria-label="Navegación principal">
        {navItems.map(({ label, icon: Icon, count }) => { const target = label === 'Inicio' ? 'Tendencias' : label === 'Explorar' ? 'Últimos Envíos' : label === 'Empleos' ? 'Vacantes & Freelance' : 'Showcase Projects'; return <button key={label} className={`nav-item ${activeTab === target ? 'active' : ''}`} onClick={() => setActiveTab(target)}><Icon size={17} /><span>{label}</span>{count && <span className="nav-count">{count}</span>}</button> })}
      </nav>
    </div>
    <div className="sidebar-section tags-section"><div className="section-heading"><p className="eyebrow">Tus temas</p><button className="icon-button" aria-label="Editar temas"><MoreHorizontal size={16} /></button></div>{tags.map(tag => <button key={tag} className={`tag-link tag-${tag}`} onClick={() => setActiveTab(tag === 'empleos' ? 'Vacantes & Freelance' : tag === 'react' || tag === 'nextjs' ? 'Últimos Envíos' : 'Tendencias')}><Hash size={14} />{tag}</button>)}<button className="see-all">Ver todos los temas <ChevronDown size={14} /></button></div>
    <div className="sidebar-cta"><div className="cta-icon"><PenLine size={16} /></div><strong>Comparte lo que sabes</strong><p>Tu experiencia puede desbloquear la de alguien más.</p><button className="text-button" onClick={() => window.location.href = '/create'}>Crear publicación <Send size={14} /></button></div>
    <div className="sidebar-footer">© 2026 Avocado <span>·</span> Reglas <span>·</span> Privacidad</div>
  </aside>
}

function PostCard({ post, onUnlock }: { post: typeof posts[number]; onUnlock: () => void }) {
  const router = useRouter(); const [voted, setVoted] = useState(false); const [saved, setSaved] = useState(false)
  const openPost = (e?: React.MouseEvent<HTMLElement>) => { if (e?.target instanceof HTMLElement && e.target.closest('button, a, input, textarea, select')) return; router.push(`/post/${post.id}`) }
  return <article className={`post-card ${post.type === 'job' ? 'job-card' : ''}`} onClick={openPost} onKeyDown={e => e.key === 'Enter' && openPost()} role="link" tabIndex={0}>
    {post.type === 'job' && <div className="job-line" />}
    <div className="post-top"><div className="author-row"><Avatar initials={post.initials} tone={post.color} /><div><div className="author-name">{post.author} {post.badge === 'Staff Avocado' && <ShieldCheck size={13} className="verified" />}</div><div className="post-meta">{post.badge} <span>·</span> {post.time}</div></div></div><button className="icon-button" aria-label="Más opciones"><MoreHorizontal size={18} /></button></div>
    <div className="post-type-label">{post.type === 'job' ? 'VACANTE / PROYECTO' : post.type === 'showcase' ? 'MOSTRAR PROYECTO' : 'POST NORMAL'}</div><h2>{post.title}</h2><p className="post-excerpt">{post.excerpt}</p>
    <div className="stack-row">{post.stack.map(item => <span className={`stack-badge stack-${item.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`} key={item}>{item}</span>)}</div>
    {post.type === 'job' && <div className="job-details"><div><span className="detail-label">Presupuesto</span><strong>{post.budget}</strong></div><div><span className="detail-label">Modalidad</span><strong>Remoto · Contrato</strong></div><button className="unlock-button" onClick={onUnlock}><LockKeyhole size={14} /> Ver contacto directo</button></div>}
    <div className="post-footer"><button className={`vote-button ${voted ? 'voted' : ''}`} onClick={() => setVoted(!voted)}><ArrowBigUp size={17} fill={voted ? 'currentColor' : 'none'} />{post.votes + (voted ? 1 : 0)}</button><button className="engagement"><MessageCircle size={16} />{post.comments} comentarios</button><span className="footer-spacer" /><button className={`icon-button ${saved ? 'saved' : ''}`} onClick={() => setSaved(!saved)} aria-label="Guardar"><Bookmark size={17} fill={saved ? 'currentColor' : 'none'} /></button><button className="icon-button" aria-label="Compartir"><Share2 size={16} /></button></div>
  </article>
}

function RightSidebar({ onUnlock }: { onUnlock: () => void }) {
  return <aside className="right-sidebar"><section className="widget"><div className="widget-title"><span>Conversaciones en fuego</span><Flame size={16} /></div>{[['¿El fin de los microservicios?', '128 respuestas'], ['Bun vs Node: batalla final', '84 respuestas'], ['IA generativa en producción', '57 respuestas']].map(([title, replies], i) => <button className="trend-item" key={title} onClick={() => onUnlock()}><span className="trend-number">0{i + 1}</span><span><strong>{title}</strong><small>{replies}</small></span></button>)}<button className="see-all">Ver todas las tendencias <ArrowBigUp size={14} /></button></section><section className="widget opportunities"><div className="widget-title"><span>Oportunidades destacadas</span><BriefcaseBusiness size={16} /></div><div className="mini-job"><div className="mini-job-top"><span className="verified-pill"><CheckCircle2 size={12} /> Verificada</span><span className="mini-time">3d restantes</span></div><strong>Frontend Engineer · React</strong><p>Producto B2B · Remoto en Latam</p><div className="mini-job-bottom"><span>$40–55 / hr</span><button onClick={onUnlock}>Ver detalles <ArrowBigUp size={13} /></button></div></div><div className="mini-job"><div className="mini-job-top"><span className="verified-pill"><CheckCircle2 size={12} /> Verificada</span><span className="mini-time">5d restantes</span></div><strong>DevOps / Cloud Engineer</strong><p>Startup seed · España / Remoto</p><div className="mini-job-bottom"><span>Proyecto fijo</span><button onClick={onUnlock}>Ver detalles <ArrowBigUp size={13} /></button></div></div></section><section className="widget community-widget"><div className="widget-title"><span>La comunidad</span><Users size={16} /></div><div className="community-stats"><div><strong>18.4k</strong><small>miembros</small></div><div><strong>2.1k</strong><small>publicaciones</small></div><div><strong>94%</strong><small>responden</small></div></div><div className="online-line"><span className="online-dot" /> 342 devs conectados ahora</div></section><div className="avocado-note"><div className="avocado-mark">A</div><div><strong>Impulsado por Avocado Studio</strong><p>Contenido técnico curado automáticamente, revisado por la comunidad.</p></div></div></aside>
}

function PublishModal({ onClose }: { onClose: () => void }) {
  const [mode, setMode] = useState('Post Normal'); const [preview, setPreview] = useState(false)
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="publish-modal" role="dialog" aria-modal="true" aria-labelledby="publish-title"><div className="modal-header"><div><p className="eyebrow">Nueva publicación</p><h2 id="publish-title">¿Qué quieres compartir?</h2></div><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={20} /></button></div><div className="publish-tabs">{['Post Normal', 'Publicar Vacante / Proyecto', 'Mostrar Proyecto'].map(item => <button key={item} className={mode === item ? 'selected' : ''} onClick={() => setMode(item)}>{item}</button>)}</div><div className="editor-toolbar"><span className="mono-label">MARKDOWN</span><button className={preview ? 'tool-active' : ''} onClick={() => setPreview(!preview)}>{preview ? 'Editar' : 'Vista previa'}</button></div>{preview ? <div className="preview-pane"><p className="eyebrow">Vista previa</p><h3>Comparte algo que valga la pena leer</h3><p>Tu publicación aparecerá aquí con formato Markdown.</p></div> : <textarea className="editor" placeholder={mode === 'Publicar Vacante / Proyecto' ? 'Describe el proyecto, stack, presupuesto y modalidad...' : 'Escribe algo que la comunidad quiera conversar...'} aria-label="Contenido de la publicación" /> }<div className="modal-bottom"><div className="stack-picker"><Tag size={15} /><span>Añadir tags</span><span className="stack-badge">React</span><span className="stack-badge">+</span></div><button className="publish-button" onClick={onClose}>Publicar <Send size={15} /></button></div></section></div>
}

function AuthModal({ onClose }: { onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="auth-modal" role="dialog" aria-modal="true" aria-labelledby="auth-title"><button className="modal-close icon-button" onClick={onClose} aria-label="Cerrar"><X size={19} /></button><div className="lock-orb"><LockKeyhole size={20} /></div><p className="eyebrow">Contacto directo</p><h2 id="auth-title">Desbloquea esta oportunidad</h2><p>Regístrate en 1 clic con GitHub o Google para acceder a los datos de contacto y unirte a la conversación.</p><button className="oauth-button github-button"><Code2 size={17} /> Continuar con GitHub</button><button className="oauth-button google-button"><span className="google-g">G</span> Continuar con Google</button><small>Al continuar aceptas nuestras reglas de comunidad.</small></section></div> }

export function CommunityHub() {
  const [activeTab, setActiveTab] = useState('Tendencias'); const [search, setSearch] = useState(''); const [publishOpen, setPublishOpen] = useState(false); const [authOpen, setAuthOpen] = useState(false); const [mobileMenu, setMobileMenu] = useState(false)
  const filteredPosts = useMemo(() => posts.filter(p => (activeTab === 'Tendencias' || (activeTab === 'Últimos Envíos' && p.id > 1) || (activeTab === 'Vacantes & Freelance' && p.type === 'job') || (activeTab === 'Showcase Projects' && p.type === 'showcase')) && `${p.title} ${p.excerpt} ${p.stack.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [activeTab, search])
  return <div className="app-shell"><header className="topbar"><button className="mobile-menu-button icon-button" onClick={() => setMobileMenu(!mobileMenu)} aria-label="Abrir menú"><Menu size={20} /></button><div className="brand"><span className="brand-mark">&gt;_</span><span>a<span className="brand-accent">vocado</span></span></div><div className="search-wrap"><Search size={17} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar discusiones, tags, personas..." aria-label="Buscar" /><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-button notification" aria-label="Notificaciones"><Bell size={18} /><span /></button><button className="publish-button top-publish" onClick={() => window.location.href = '/create'}><Plus size={16} /> Publicar</button><Avatar initials="JD" tone="blue" /></div></header><div className={`mobile-drawer ${mobileMenu ? 'open' : ''}`}><div className="drawer-head"><strong>Menú</strong><button className="icon-button" onClick={() => setMobileMenu(false)} aria-label="Cerrar menú"><X size={18} /></button></div><LeftSidebar onPublish={() => setPublishOpen(true)} activeTab={activeTab} setActiveTab={setActiveTab} /></div><div className="layout"><LeftSidebar onPublish={() => setPublishOpen(true)} activeTab={activeTab} setActiveTab={setActiveTab} /><main className="feed"><div className="feed-heading"><div><p className="eyebrow">Viernes, 31 de agosto</p><h1>Tu feed <span className="live-dot" /></h1></div><button className="filter-button">Para ti <ChevronDown size={15} /></button></div><div className="feed-tabs" role="tablist">{tabs.map(({ label, icon: Icon }) => <button key={label} role="tab" aria-selected={activeTab === label} className={activeTab === label ? 'active' : ''} onClick={() => setActiveTab(label)}><Icon size={15} />{label}</button>)}</div><div className="post-list">{filteredPosts.length ? filteredPosts.map(post => <PostCard key={post.id} post={post} onUnlock={() => setAuthOpen(true)} />) : <div className="empty-state"><Search size={24} /><h2>No encontramos publicaciones</h2><p>Prueba con otra búsqueda o explora las tendencias.</p></div>}</div></main><RightSidebar onUnlock={() => setAuthOpen(true)} /></div><nav className="bottom-nav" aria-label="Navegación móvil">{navItems.slice(0, 4).map(({ label, icon: Icon }) => <button key={label} onClick={() => setActiveTab(label === 'Empleos' ? 'Vacantes & Freelance' : label === 'Inicio' ? 'Tendencias' : label)} className={label === 'Inicio' && activeTab === 'Tendencias' ? 'active' : ''}><Icon size={19} /><span>{label}</span></button>)}</nav>{publishOpen && <PublishModal onClose={() => setPublishOpen(false)} />}{authOpen && <AuthModal onClose={() => setAuthOpen(false)} />}</div>
}
