'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowBigUp, Bookmark, MessageCircle, Share2, Send } from 'lucide-react'

const post = { author: 'Avocado', initials: 'AV', time: 'hace 2h', tag: 'nextjs', title: 'Next.js 16: lo que realmente cambia para tu próximo proyecto', excerpt: 'Un recorrido práctico por Cache Components, React Compiler y las nuevas APIs que ya puedes usar.', stack: ['Next.js', 'React', 'Rendimiento'], votes: 248, comments: 38 }

export default function PostPage() {
  return <main className="post-detail-page"><div className="post-detail-wrap"><Link href="/" className="back-link"><ArrowLeft size={16} /> Volver al feed</Link><article className="post-detail-card"><div className="detail-author"><div className="avatar avatar-cyan">{post.initials}</div><div><strong>{post.author}</strong><span>Staff Avocado · {post.time} · #{post.tag}</span></div></div><h1>{post.title}</h1><p className="detail-lead">{post.excerpt}</p><div className="stack-row">{post.stack.map(item => <span className="stack-badge" key={item}>{item}</span>)}</div><div className="detail-copy"><p>La nueva versión de Next.js llega con cambios importantes para quienes construyen productos modernos. En este artículo repasamos qué novedades importan realmente y cómo incorporarlas sin reescribir tu aplicación.</p><h2>Cache Components y rendimiento</h2><p>Cache Components permite definir con más precisión qué partes de una página pueden reutilizarse. Combinado con Server Components, ayuda a entregar experiencias rápidas manteniendo el código simple.</p><h2>Qué deberías probar primero</h2><p>Empieza por las rutas que más tráfico reciben, mide el resultado y adopta las nuevas APIs de forma incremental. No necesitas migrar todo de una vez para obtener beneficios.</p></div><div className="detail-actions"><button className="vote-button"><ArrowBigUp size={17} /> {post.votes}</button><button className="engagement"><MessageCircle size={16} /> {post.comments} comentarios</button><span className="footer-spacer" /><button className="icon-button" aria-label="Guardar"><Bookmark size={17} /></button><button className="icon-button" aria-label="Compartir"><Share2 size={16} /></button></div></article><section className="comments-card"><div><h2>Conversación</h2><p>{post.comments} respuestas de la comunidad</p></div><button className="publish-button"><Send size={15} /> Responder</button></section></div></main>
}
